# application.yml

spring:
  datasource:
    url: jdbc:h2:mem:test_db
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


